---
- hosts: localhost
  connection: local
  vars:
    #- ansible_python_interpreter: python2
  tasks:
    - name: boto
      pip:
        name: boto
    - name: Create an Ec2 instance
      ec2: 
        key_name: pathu0404
        instance_type: t2.micro
        image: ami-05fa00d4c63e32376
        wait: yes
        # group: webserver
        count: 1
        vpc_subnet_id: subnet-03c9ee3fac89651ef
        assign_public_ip: yes
        region: us-east-1
