---
- hosts: localhost
  tasks:
  - name: create ami for ec2 user
    ec2_ami:
      region: *
      instance_id: *
      wait: yes
      aws_access_key: *
      aws_secret_key: *
      name: ami
      tags:
         Name: ansible ami
         Service: TestService
    register: image      
