---
- hosts: localhost
  vars:
    - awsregion: *
    - instanceids: *
  tasks:
    - name: Create an Ec2 instance
      ec2: 
        key_name: *
        instance_type: *
        image: *
        wait: yes
        # group: webserver
        count: 2
        vpc_subnet_id: subnet-*
        assign_public_ip: yes
        region: "{{ awsregion }}"
        ## register: ec2_output
        aws_access_key: *
        aws_secret_key: *
