---
- hosts: localhost
  tasks:
    - name: Create snapshot
      ec2_snapshot:
         description: snapshot
         instance_id: *
         aws_access_key: *
         aws_secret_key: *
         region: *
         wait: yes
         device_name: *
         debug_botocore_endpoint_logs: no
         last_snapshot_min_age: 0




